/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  base: [{type: 'autogenerated', dirName: '.'}],
  common: [{type: 'autogenerated', dirName: 'common'}],
  linux: [{type: 'autogenerated', dirName: 'linux'}],
  windows: [{type: 'autogenerated', dirName: 'windows'}],
  python: [{type: 'autogenerated', dirName: 'python'}],
  discord: [{type: 'autogenerated', dirName: 'discord'}],
  '1C': [{type: 'autogenerated', dirName: '1C'}],
};

module.exports = sidebars;
